### ISSUE TITLE
Trilateration

### ISSUE THREAD

**Issue by FXUDarkNova** [F-Army/arduino-dw1000-ng#149]
Testing out the StandardRTLSAnchorMain and wondering how I measure the positions of each of my anchor to add to the Position position_self = {0, 0}; so it gets the correction positioning. Also if i attached 3 anchors to a robot and used a tag would trilateration work or would I need to look at alternative method?

**Comment by Sonic0** [comment]
Which is the context of your application? 
In standard trilateration application, the anchors are fixed. In this case position_self = {0,0}  is an cartesian coordinate x=0, y=0 (usually for Main anchor).

**Comment by FXUDarkNova** [comment]
My idea is all 3 anchors will fixed onto the robot and will then move to wherever the tag is located

**Comment by anacromaniac** [comment]
I think you could adopt an alternative approach without using positioning but rather just distance calculation, as the robot will read a reduction in the distance he'll know he is moving in the right direction. Otherwise probably the best approach overall would be to use Phase difference of arrival OR Angle of Arrival algorithms to calculate the position of the tag relative to the robot. Too bad we didn't have time to experiment with PDoA and AoA, but as far as i know there is a lot of scientific literature about it just a google scholar search away. Hope this was of help!

**Comment by Sonic0** [comment]
Yes, I think the same! A simple solution is a distance calculator.

**Comment by FXUDarkNova** [comment]
Ok thank you for your help do you think would be better to use just two anchors instead of three then?

**Comment by FXUDarkNova** [comment]
I have attempted triangulation using two anchors and one tag which seems to be working I just know need to figure out how to do heading any ideas?

**Comment by Sonic0** [comment]
Whit two anchors the position of the tag will be inaccurate, but working.
I have no idea at the moment for the algorithm.

**Comment by FXUDarkNova** [comment]
Iv managed to get something working using to anchors and one tag work pretty well actually.
